version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: sistema_gastos_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: sistema_gastos_clientes
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
