spring.application.name=sistema_gastos_clientes

spring.datasource.url=jdbc:mysql://localhost:3307/sistema_gastos_clientes_db
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

server.port=8080

spring.thymeleaf.cache=false

# Seguridad
spring.security.user.name=admin
spring.security.user.password=admin
spring.security.user.roles=CONTADOR

# Logging
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql=TRACE
